pipeline:
  name: Sample
  identifier: Sample
  projectIdentifier: Harness_POC
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: praneeshtech
        repoName: python-pipeline-samples
        build: <+input>
  stages:
    - stage:
        name: "Listing directories "
        identifier: Listing_directories
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Directory Check
                  identifier: Directory_Check
                  spec:
                    shell: Sh
                    command: |-
                      pwd
                      ls -ltra
    - stage:
        name: "Docker Build "
        identifier: Docker_Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
            paths: []
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: docker_connector
                    repo: python-pipeline-samples
                    tags:
                      - vijaysoundarapandiyan/python-pipeline-samples
          buildIntelligence:
            enabled: false
